### ISSUE TITLE
Unable to pull from https://artifactory.delivery.puppetlabs.net/artifactory/api/gems/rubygems/

### ISSUE THREAD

**Issue by sseebald** [puppetlabs/gatling-puppet-load-test#407]
We're trying to use Gatling for scale testing a new Puppet environment we're standing up, but hitting an early roadblock. When executing the "bundle install" after cloning the repo, we're getting:

Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://artifactory.delivery.puppetlabs.net/artifactory/api/gems/rubygems/

There doesn't seem to be anything on our side blocking this.

Sorry if this isn't the right place to post this - Any guidance on things to try so we can use Gatling?

**Comment by RandellP** [comment]
Sorry, artifictory is only internal.  There are other things in it as well that are only internal.  We have a desire to make gplt usable outside of puppet, but haven't been able to spare the resources to make that happen yet.  There is nothing that theoretically can't be done outside of puppet.  You would basically have to do most of the setup manually.  In theory the running of the test itself shouldn't have any internal dependencies.  But you would have to read through the setup and make sure to do all the things it does.

**Comment by sseebald** [comment]
Ah bummer, that's what I was afraid of!  We'll check it out on our side and see if we're able to make it work. Thank you!

**Comment by RandellP** [comment]
yeah... the setup code is not something we are very happy with... it's been around a long time and due for an overhaul. But in the end... most of what it is doing isn't too hard to do manually... Good luck. :)
